### ISSUE TITLE
docker-compose up fails with bundler error

### ISSUE THREAD

**Issue by YaguraStation** [openstreetmap/stateofthemap-2020#39]
```
$ sudo docker-compose up
Creating stateofthemap-2020_app_1 ... done
Attaching to stateofthemap-2020_app_1
app_1  | /usr/local/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /app/Gemfile.lock. (Gem::GemNotFoundException)
app_1  | To update to the latest version installed on your system, run `bundle update --bundler`.
app_1  | To install the missing version, run `gem install bundler:2.1.4`
app_1  | 	from /usr/local/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
app_1  | 	from /usr/local/bundle/bin/bundle:23:in `<main>'
stateofthemap-2020_app_1 exited with code 1
```

**Comment by tyrasd** [comment]
hmm, it doesn't work for me neither. :( did you try a local installation without docker (https://github.com/openstreetmap/stateofthemap-2020#local-installation)? that's how I run it on my machine.

**Comment by YaguraStation** [comment]
Yeah, will work with my own `Gemfile.lock` for now and try and remediate the Docker setup later.

**Comment by YaguraStation** [comment]
Simply having `docker-compose up` also build with `--build` does the trick.
